"""add site columns

Revision ID: 3e427fca4752
Revises: d95becbf0bb1
Create Date: 2026-05-25 13:36:24.267473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e427fca4752'
down_revision: Union[str, None] = 'd95becbf0bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('import_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'executions', 'imports', ['import_id'], ['id'])
    op.add_column('sites', sa.Column('date_handover', sa.Date(), nullable=True))
    op.add_column('sites', sa.Column('techno', sa.String(length=100), nullable=True))
    op.add_column('sites', sa.Column('passive_handler', sa.String(length=50), nullable=True))
    op.add_column('sites', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('priorite', sa.String(length=20), nullable=True))
    op.add_column('sites', sa.Column('typologie', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'typologie')
    op.drop_column('sites', 'priorite')
    op.drop_column('sites', 'longitude')
    op.drop_column('sites', 'latitude')
    op.drop_column('sites', 'passive_handler')
    op.drop_column('sites', 'techno')
    op.drop_column('sites', 'date_handover')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_column('executions', 'import_id')
    # ### end Alembic commands ###
