"""init

Revision ID: d95becbf0bb1
Revises: 
Create Date: 2026-05-22 12:21:29.164469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95becbf0bb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_site', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.Enum('GRID_ONLY', 'GRID_GEN', 'SOLAR_ONLY', 'GEN_ONLY', name='categorieenum'), nullable=False),
    sa.Column('sbc', sa.Enum('Afro', 'CCS', 'Hammer', name='sbcenum'), nullable=False),
    sa.Column('sto', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('type_alimentation', sa.String(length=50), nullable=True),
    sa.Column('cycle', sa.String(length=1), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_acceptance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_site')
    )
    op.create_index('ix_sites_sbc_sto_cat_actif', 'sites', ['sbc', 'sto', 'categorie', 'actif'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'sbc', 'client', name='roleenum'), nullable=False),
    sa.Column('sbc_associe', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('niveau', sa.Enum('critique', 'avertissement', 'information', name='niveaualerteenum'), nullable=False),
    sa.Column('type_alerte', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('nouvelle', 'vue', 'prise_en_charge', 'fermee', name='statutalerteenum'), nullable=False),
    sa.Column('prise_en_charge_par', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prise_en_charge_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_site_id', 'alerts', ['site_id'], unique=False)
    op.create_index('ix_alerts_statut_niveau', 'alerts', ['statut', 'niveau'], unique=False)
    op.create_index('ix_alerts_type_alerte', 'alerts', ['type_alerte'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_fichier', sa.String(length=200), nullable=False),
    sa.Column('date_import', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('importe_par', sa.Integer(), nullable=True),
    sa.Column('nb_lignes_brut', sa.Integer(), nullable=True),
    sa.Column('nb_integres', sa.Integer(), nullable=True),
    sa.Column('nb_doublons', sa.Integer(), nullable=True),
    sa.Column('nb_max_depasse', sa.Integer(), nullable=True),
    sa.Column('nb_non_trouves', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('succes', 'echec', 'partiel', name='statutimportenum'), nullable=False),
    sa.Column('detail_erreurs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['importe_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('passage_num', sa.Integer(), nullable=False),
    sa.Column('total_passages', sa.Integer(), nullable=False),
    sa.Column('mois_num', sa.Integer(), nullable=False),
    sa.Column('mois_nom', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('date_planifiee', sa.Date(), nullable=False),
    sa.Column('date_planifiee_initiale', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('Prevu', 'Fait', 'Non_effectue', name='statutpassageenum'), nullable=False),
    sa.Column('is_replanifie', sa.Boolean(), nullable=False),
    sa.Column('impossible_a_rattraper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'mois_num', 'annee', 'passage_num', name='uq_passage_site_mois')
    )
    op.create_index('ix_passages_annee_statut', 'passages', ['annee', 'statut'], unique=False)
    op.create_index('ix_passages_date_planifiee', 'passages', ['date_planifiee'], unique=False)
    op.create_index('ix_passages_site_mois_annee_statut', 'passages', ['site_id', 'mois_num', 'annee', 'statut'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('date_execution', sa.Date(), nullable=False),
    sa.Column('wo_ticket', sa.String(length=50), nullable=False),
    sa.Column('operateur', sa.String(length=100), nullable=True),
    sa.Column('niveau_carburant', sa.Integer(), nullable=True),
    sa.Column('ch_ge', sa.Integer(), nullable=True),
    sa.Column('tension_batterie', sa.Float(), nullable=True),
    sa.Column('snags', sa.Text(), nullable=True),
    sa.Column('checklist_ok', sa.Boolean(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id')
    )
    op.create_index('ix_executions_date_execution', 'executions', ['date_execution'], unique=False)
    op.create_index('ix_executions_site_id', 'executions', ['site_id'], unique=False)
    op.create_index('ix_executions_wo_ticket', 'executions', ['wo_ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_wo_ticket', table_name='executions')
    op.drop_index('ix_executions_site_id', table_name='executions')
    op.drop_index('ix_executions_date_execution', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_passages_site_mois_annee_statut', table_name='passages')
    op.drop_index('ix_passages_date_planifiee', table_name='passages')
    op.drop_index('ix_passages_annee_statut', table_name='passages')
    op.drop_table('passages')
    op.drop_table('imports')
    op.drop_index('ix_alerts_type_alerte', table_name='alerts')
    op.drop_index('ix_alerts_statut_niveau', table_name='alerts')
    op.drop_index('ix_alerts_site_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_index('ix_sites_sbc_sto_cat_actif', table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
